### ISSUE TITLE
OpenFisca support for weekly periods

### ISSUE THREAD

**Issue by nigelcharman** [OrganicCoders/openfisca-aotearoa#1]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

The [NZ Compensation for Live Organ Donors Act 2016](http://www.legislation.govt.nz/act/public/2016/0096/latest/whole.html?search=ts_act%40bill%40regulation%40deemedreg_live+organ_resel_25_a) requires that [weekly earnings are calculated](http://www.legislation.govt.nz/act/public/2016/0096/latest/whole.html?search=ts_act%40bill%40regulation%40deemedreg_live+organ_resel_25_a#DLM6965112).

Income in NZ is typically based on a Weekly, Fortnightly, 4 Weekly or Monthly basis.

OpenFisca Periods currently supports MONTH, YEAR and ETERNITY.

We currently believe that we will need WEEK periods to make this work.

_To be updated as we discover more..._

**Comment by MattiSG** [comment]
Hey @nigelcharman! Thanks for opening that issue 😃 
However, it's in your fork of `openfisca-aotearoa`, which doesn't make it very easy to find for the wider OpenFisca community :wink:

I believe this issue would be best opened in https://github.com/openfisca/openfisca-core/issues. Could you migrate it there? 🙂

**Comment by MattiSG** [comment]
Linking to [this PR](https://github.com/ServiceInnovationLab/openfisca-aotearoa/pull/13/files) or [that one](https://github.com/ServiceInnovationLab/openfisca-aotearoa/pull/16) would be a great example 🙂

**Comment by nigelcharman** [comment]
I've created openfisca/openfisca-core#670 and will close this one.
